[package]
name = "bytepath"
version = "0.1.0"
authors = ["Sebastian Richter <sebastian.richter@paessler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rapier2d = "0.8.0"

[dependencies.specs]
version = "0.16.1"
features = ["specs-derive"]

[dependencies.sdl2]
version = "0.34"
default-features = false
features = ["gfx"]

